### ISSUE TITLE
Proxy support unusable in MacOS

### ISSUE THREAD

**Issue by biaji** [RSSNext/Follow#1197]
### Describe the bug

Operating System: MacOS 13.6.9 Intel

1. Disable proxy in system settings
2. Set http proxy in Follow‘s Settings. 

It seemed Follow doesn't use proxy to do some(or all) work:

```
[2024-10-28 11:27:39.873] [info]  (main) Checking for update
[2024-10-28 11:27:40.343] [info]         Follow: Next generation information browser https://github.com/RSSNext/follow
[2024-10-28 11:27:40.344] [info]         Initialize Follow...
[2024-10-28 11:27:40.354] [info]         migration took 10ms
[2024-10-28 11:27:40.354] [info]         hydrateSettings took 9ms
[2024-10-28 11:27:40.354] [info]         setting sync took 9ms
[2024-10-28 11:27:40.354] [info]         i18n took 6ms
[2024-10-28 11:27:40.452] [info]         App is ready 588ms
[2024-10-28 11:27:40.473] [info]         hydrateDatabaseToStore took 119ms
[2024-10-28 11:27:40.474] [info]         Initialize Follow done, 130ms
[2024-10-28 11:27:40.749] [info]         App is ready 885ms
[2024-10-28 11:27:40.903] [info]         dayjs loaded:  zh-cn
[2024-10-28 11:27:43.983] [error] (main) Error while updating client Error: net::ERR_ADDRESS_UNREACHABLE
    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:2:118029)
    at SimpleURLLoaderWrapper.emit (node:events:519:28)
[2024-10-28 11:27:43.983] [error] (main) Error checking for updates Error: net::ERR_ADDRESS_UNREACHABLE
    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:2:118029)
    at SimpleURLLoaderWrapper.emit (node:events:519:28)
[2024-10-28 11:28:17.177] [error] (main) PushReceiver error: TypeError: fetch failed
    at node:internal/deps/undici/undici:13185:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async retry$3 (file:///Applications/Follow.app/Contents/Resources/app.asar/dist/main/index.js:10157:12)
    at async checkIn (file:///Applications/Follow.app/Contents/Resources/app.asar/dist/main/index.js:14967:23)
    at async gcm.default (file:///Applications/Follow.app/Contents/Resources/app.asar/dist/main/index.js:14962:19)
    at async PushReceiver2.registerIfNeeded (file:///Applications/Follow.app/Contents/Resources/app.asar/dist/main/index.js:16183:18)
    at async PushReceiver2.connect (file:///Applications/Follow.app/Contents/Resources/app.asar/dist/main/index.js:16123:5)
    at async registerPushNotifications (file:///Applications/Follow.app/Contents/Resources/app.asar/dist/main/index.js:95862:5)
[2024-10-28 11:28:17.178] [info]  (main) PushReceiver connected
```

And the proxy settings in follow didn't saved,  it's gone after restart the app.

### Feed Info

none.

### App Type

Electron / App

### Operating System

macOS

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by lawvs** [comment]
I think this issue might be related to the proxy format you entered. Could you provide additional details about the proxy configuration?

The following are several legal formats:

```
socks://localhost:1234
https://127.0.0.1:4567
```

**Comment by biaji** [comment]
> I think this issue might be related to the proxy format you entered. Could you provide additional details about the proxy configuration?
> 
> The following are several legal formats:
> 
> ```
> socks://localhost:1234
> https://127.0.0.1:4567
> ```

I tried 
```
http://xxx.xxx.com
```
and 
```
http://xxx.xxx.com:80
```
both failed.  either for save or take effect.

**Comment by lawvs** [comment]
I apologize for the inconvenience. A rare bug is causing this configuration to malfunction. You can change the proxy port, and I will resolve this issue in the next version.
