### ISSUE TITLE
Error: (intermediate value)(intermediate value)(intermediate value) is not iterable

### ISSUE THREAD

**Issue by SYYDSN** [RSSNext/Follow#1308]
### Error

(intermediate value)(intermediate value)(intermediate value) is not iterable

### Stack

```
TypeError: (intermediate value)(intermediate value)(intermediate value) is not iterable
    at file:///C:/Users/92714/AppData/Local/Follow/app-0.1.2-beta0/resources/app.asar/dist/renderer/assets/main-C2XzwSBN.js:426:12964
    at Object.useMemo (file:///C:/Users/92714/AppData/Local/Follow/app-0.1.2-beta0/resources/app.asar/dist/renderer/assets/main-C2XzwSBN.js:71:26036)
    at react_production_min.useMemo (file:///C:/Users/92714/AppData/Local/Follow/app-0.1.2-beta0/resources/app.asar/dist/renderer/assets/main-C2XzwSBN.js:10:7277)
    at SupportCreator (file:///C:/Users/92714/AppData/Local/Follow/app-0.1.2-beta0/resources/app.asar/dist/renderer/assets/main-C2XzwSBN.js:426:12931)
    at Nh (file:///C:/Users/92714/AppData/Local/Follow/app-0.1.2-beta0/resources/app.asar/dist/renderer/assets/main-C2XzwSBN.js:71:19019)
    at Vk (file:///C:/Users/92714/AppData/Local/Follow/app-0.1.2-beta0/resources/app.asar/dist/renderer/assets/main-C2XzwSBN.js:73:48765)
    at Uk (file:///C:/Users/92714/AppData/Local/Follow/app-0.1.2-beta0/resources/app.asar/dist/renderer/assets/main-C2XzwSBN.js:73:43991)
    at Tk (file:///C:/Users/92714/AppData/Local/Follow/app-0.1.2-beta0/resources/app.asar/dist/renderer/assets/main-C2XzwSBN.js:73:43912)
    at Ik (file:///C:/Users/92714/AppData/Local/Follow/app-0.1.2-beta0/resources/app.asar/dist/renderer/assets/main-C2XzwSBN.js:73:43752)
    at Nk (file:///C:/Users/92714/AppData/Local/Follow/app-0.1.2-beta0/resources/app.asar/dist/renderer/assets/main-C2XzwSBN.js:73:39720)
    at Ek (file:///C:/Users/92714/AppData/Local/Follow/app-0.1.2-beta0/resources/app.asar/dist/renderer/assets/main-C2XzwSBN.js:73:40622)
    at jg (file:///C:/Users/92714/AppData/Local/Follow/app-0.1.2-beta0/resources/app.asar/dist/renderer/assets/main-C2XzwSBN.js:71:3546)
    at file:///C:/Users/92714/AppData/Local/Follow/app-0.1.2-beta0/resources/app.asar/dist/renderer/assets/main-C2XzwSBN.js:73:37840
```

### Environment

**App Version**: 0.1.2-beta.0
**OS**: Windows
**User Agent**: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.1.2-beta.0 Chrome/130.0.6723.44 Electron/33.0.0 Safari/537.36
**Env**: electron
**Browser**: Chrome

**Comment by hyoban** [comment]
Can you provide more information on how to reproduce this issue?

**Comment by lyrl** [comment]
@hyoban ![Image](https://github.com/user-attachments/assets/50e77d2b-afb7-40ac-b1b4-b5b8c0db76fe)

**Comment by lawvs** [comment]
We apologize for the inconvenience. You can try to rebuild the database in settings to fix it. We will address this issue in the next release.

![Image](https://github.com/user-attachments/assets/e033b4d5-d3a2-4e70-9f53-cb1b72990a88)

Blame to https://github.com/RSSNext/Follow/pull/1167
