### ISSUE TITLE
Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

### ISSUE THREAD

**Issue by fanzhg** [RSSNext/Follow#1368]
### Error

Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

### Stack

```
Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Rg (file:///Follow/app-0.1.2-nightly20241103/resources/app.asar/dist/renderer/assets/main-DJ4pMuMc.js:73:54766)
    at mt (file:///Follow/app-0.1.2-nightly20241103/resources/app.asar/dist/renderer/assets/main-DJ4pMuMc.js:71:8658)
    at vt (file:///Follow/app-0.1.2-nightly20241103/resources/app.asar/dist/renderer/assets/main-DJ4pMuMc.js:71:10280)
    at tn (file:///Follow/app-0.1.2-nightly20241103/resources/app.asar/dist/renderer/assets/main-DJ4pMuMc.js:71:12726)
    at Xi (file:///Follow/app-0.1.2-nightly20241103/resources/app.asar/dist/renderer/assets/main-DJ4pMuMc.js:73:1613)
    at Vk (file:///Follow/app-0.1.2-nightly20241103/resources/app.asar/dist/renderer/assets/main-DJ4pMuMc.js:73:49178)
    at Uk (file:///Follow/app-0.1.2-nightly20241103/resources/app.asar/dist/renderer/assets/main-DJ4pMuMc.js:73:43991)
    at Tk (file:///Follow/app-0.1.2-nightly20241103/resources/app.asar/dist/renderer/assets/main-DJ4pMuMc.js:73:43912)
    at Ik (file:///Follow/app-0.1.2-nightly20241103/resources/app.asar/dist/renderer/assets/main-DJ4pMuMc.js:73:43752)
    at Nk (file:///Follow/app-0.1.2-nightly20241103/resources/app.asar/dist/renderer/assets/main-DJ4pMuMc.js:73:39720)
    at Ek (file:///Follow/app-0.1.2-nightly20241103/resources/app.asar/dist/renderer/assets/main-DJ4pMuMc.js:73:40622)
    at jg (file:///Follow/app-0.1.2-nightly20241103/resources/app.asar/dist/renderer/assets/main-DJ4pMuMc.js:71:3546)
    at file:///Follow/app-0.1.2-nightly20241103/resources/app.asar/dist/renderer/assets/main-DJ4pMuMc.js:73:37840
```

### Environment

**App Version**: 0.1.2-nightly.20241103
**OS**: Windows
**User Agent**: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.1.2-nightly.20241103 Chrome/130.0.6723.59 Electron/33.0.2 Safari/537.36
**Env**: electron
**Browser**: Chrome

**Comment by hyoban** [comment]
Can you provide more information on how to reproduce this issue?

**Comment by fanzhg** [comment]
![Image](https://github.com/user-attachments/assets/eb7bec79-9f00-41c6-9f03-aebb09b2dd06)

**Comment by hyoban** [comment]
Fixed in https://github.com/RSSNext/Follow/commit/7d38cb6d2f814d3b6012b66ba6024c05b6edcf2d
