### ISSUE TITLE
Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

### ISSUE THREAD

**Issue by Mark-Josh** [RSSNext/Follow#1478]
### Error

Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

### Stack

```
Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Rg (file:///Applications/Follow.app/Contents/Resources/app.asar/dist/renderer/assets/main-CflahMxd.js:73:54766)
    at mt (file:///Applications/Follow.app/Contents/Resources/app.asar/dist/renderer/assets/main-CflahMxd.js:71:8658)
    at vt (file:///Applications/Follow.app/Contents/Resources/app.asar/dist/renderer/assets/main-CflahMxd.js:71:10280)
    at tn (file:///Applications/Follow.app/Contents/Resources/app.asar/dist/renderer/assets/main-CflahMxd.js:71:12726)
    at Xi (file:///Applications/Follow.app/Contents/Resources/app.asar/dist/renderer/assets/main-CflahMxd.js:73:1613)
    at Vk (file:///Applications/Follow.app/Contents/Resources/app.asar/dist/renderer/assets/main-CflahMxd.js:73:49178)
    at Uk (file:///Applications/Follow.app/Contents/Resources/app.asar/dist/renderer/assets/main-CflahMxd.js:73:43991)
    at Tk (file:///Applications/Follow.app/Contents/Resources/app.asar/dist/renderer/assets/main-CflahMxd.js:73:43912)
    at Ik (file:///Applications/Follow.app/Contents/Resources/app.asar/dist/renderer/assets/main-CflahMxd.js:73:43752)
    at Nk (file:///Applications/Follow.app/Contents/Resources/app.asar/dist/renderer/assets/main-CflahMxd.js:73:39720)
    at Ek (file:///Applications/Follow.app/Contents/Resources/app.asar/dist/renderer/assets/main-CflahMxd.js:73:40622)
    at jg (file:///Applications/Follow.app/Contents/Resources/app.asar/dist/renderer/assets/main-CflahMxd.js:71:3546)
    at Wk (file:///Applications/Follow.app/Contents/Resources/app.asar/dist/renderer/assets/main-CflahMxd.js:73:45654)
    at Pk (file:///Applications/Follow.app/Contents/Resources/app.asar/dist/renderer/assets/main-CflahMxd.js:73:44536)
    at Gk (file:///Applications/Follow.app/Contents/Resources/app.asar/dist/renderer/assets/main-CflahMxd.js:73:39505)
    at fn (file:///Applications/Follow.app/Contents/Resources/app.asar/dist/renderer/assets/main-CflahMxd.js:58:1729)
    at MessagePort.xn (file:///Applications/Follow.app/Contents/Resources/app.asar/dist/renderer/assets/main-CflahMxd.js:58:2141)
```

### Environment

**App Version**: 0.1.2-nightly.20241103
**OS**: macOS
**User Agent**: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.1.2-nightly.20241103 Chrome/130.0.6723.59 Electron/33.0.2 Safari/537.36
**Env**: electron
**Browser**: Chrome
**Session Trace Id**: `k7swLQS1J8x641j3Dv3SJ`

### Sentry Trace ID
xHE2EME8oEed7pJRWIBFX

**Comment by hyoban** [comment]
Duplicate of #1479
