### ISSUE TITLE
Error: (intermediate value)(intermediate value)(intermediate value) is not iterable

### ISSUE THREAD

**Issue by starpastoral** [RSSNext/Follow#1515]
### Error

(intermediate value)(intermediate value)(intermediate value) is not iterable

### Stack

```
TypeError: (intermediate value)(intermediate value)(intermediate value) is not iterable
    at file:///Applications/Follow.app/Contents/Resources/app.asar/dist/renderer/assets/main-WYXPxdLY.js:456:15446
    at Object.useMemo (file:///Applications/Follow.app/Contents/Resources/app.asar/dist/renderer/assets/main-WYXPxdLY.js:71:26036)
    at react_production_min.useMemo (file:///Applications/Follow.app/Contents/Resources/app.asar/dist/renderer/assets/main-WYXPxdLY.js:10:7277)
    at SupportCreator (file:///Applications/Follow.app/Contents/Resources/app.asar/dist/renderer/assets/main-WYXPxdLY.js:456:15413)
    at Nh (file:///Applications/Follow.app/Contents/Resources/app.asar/dist/renderer/assets/main-WYXPxdLY.js:71:19019)
    at Vk (file:///Applications/Follow.app/Contents/Resources/app.asar/dist/renderer/assets/main-WYXPxdLY.js:73:48765)
    at Uk (file:///Applications/Follow.app/Contents/Resources/app.asar/dist/renderer/assets/main-WYXPxdLY.js:73:43991)
    at Tk (file:///Applications/Follow.app/Contents/Resources/app.asar/dist/renderer/assets/main-WYXPxdLY.js:73:43912)
    at Ik (file:///Applications/Follow.app/Contents/Resources/app.asar/dist/renderer/assets/main-WYXPxdLY.js:73:43752)
    at Nk (file:///Applications/Follow.app/Contents/Resources/app.asar/dist/renderer/assets/main-WYXPxdLY.js:73:39720)
    at Ek (file:///Applications/Follow.app/Contents/Resources/app.asar/dist/renderer/assets/main-WYXPxdLY.js:73:40622)
    at jg (file:///Applications/Follow.app/Contents/Resources/app.asar/dist/renderer/assets/main-WYXPxdLY.js:71:3546)
    at file:///Applications/Follow.app/Contents/Resources/app.asar/dist/renderer/assets/main-WYXPxdLY.js:73:37840
```

### Environment

**App Version**: 0.2.0-beta.1
**OS**: macOS
**User Agent**: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.2.0-beta.1 Chrome/130.0.6723.59 Electron/33.0.2 Safari/537.36
**Env**: electron
**Browser**: Chrome
**Session Trace Id**: `XXxlmsVDZgm3d_8H0i-1m`

### Sentry Trace ID
lk4SfE7zaWU2daRTQBFAV

**Comment by hyoban** [comment]
Can you provide more information on how to reproduce this issue?

**Comment by starpastoral** [comment]
Every time I try to read Daring Fireball (https://daringfireball.net/feeds/articles) articles in Article view, I encounter this error. Because it happens every time, I haven't been able to read any Daring Fireball articles using Follow this month. And I can provide the specific entry ID for you to debug: 77957378050875392
Besides, other feeds are experiencing similar issues: 
https://blog.devtang.com/atom.xml
and its specific entry ID: 77400895524689920

**Comment by lawvs** [comment]
Workaround in https://github.com/RSSNext/Follow/pull/1531

You can rebuild the database in settings when you reencounter this problem.

![Image](https://github.com/user-attachments/assets/e033b4d5-d3a2-4e70-9f53-cb1b72990a88)
