### ISSUE TITLE
Error in loading "Custom CSS": Failed to execute 'setEnd' on 'Range': parameter 1 is not of type 'Node'.

### ISSUE THREAD

**Issue by RizzoTho** [RSSNext/Follow#1527]
### Error

Failed to execute 'setEnd' on 'Range': parameter 1 is not of type 'Node'.

### Stack

```
TypeError: Failed to execute 'setEnd' on 'Range': parameter 1 is not of type 'Node'.
    at file:///Applications/Follow.app/Contents/Resources/app.asar/dist/renderer/assets/css-editor-Bj0CQ1xG.js:4:2203
    at file:///Applications/Follow.app/Contents/Resources/app.asar/dist/renderer/assets/css-editor-Bj0CQ1xG.js:4:391
    at j (file:///Applications/Follow.app/Contents/Resources/app.asar/dist/renderer/assets/css-editor-Bj0CQ1xG.js:5:94)
    at Object.n [as mount] (file:///Applications/Follow.app/Contents/Resources/app.asar/dist/renderer/assets/css-editor-Bj0CQ1xG.js:4:2520)
    at file:///Applications/Follow.app/Contents/Resources/app.asar/dist/renderer/assets/css-editor-Bj0CQ1xG.js:5:1204
    at Qj (file:///Applications/Follow.app/Contents/Resources/app.asar/dist/renderer/assets/main-WYXPxdLY.js:73:26763)
    at jk (file:///Applications/Follow.app/Contents/Resources/app.asar/dist/renderer/assets/main-WYXPxdLY.js:73:36361)
    at ik (file:///Applications/Follow.app/Contents/Resources/app.asar/dist/renderer/assets/main-WYXPxdLY.js:73:34654)
    at ik (file:///Applications/Follow.app/Contents/Resources/app.asar/dist/renderer/assets/main-WYXPxdLY.js:73:34684)
    at hk (file:///Applications/Follow.app/Contents/Resources/app.asar/dist/renderer/assets/main-WYXPxdLY.js:73:34278)
    at Wk (file:///Applications/Follow.app/Contents/Resources/app.asar/dist/renderer/assets/main-WYXPxdLY.js:73:45244)
    at Pk (file:///Applications/Follow.app/Contents/Resources/app.asar/dist/renderer/assets/main-WYXPxdLY.js:73:44536)
    at Gk (file:///Applications/Follow.app/Contents/Resources/app.asar/dist/renderer/assets/main-WYXPxdLY.js:73:39505)
    at fn (file:///Applications/Follow.app/Contents/Resources/app.asar/dist/renderer/assets/main-WYXPxdLY.js:58:1729)
    at MessagePort.hn (file:///Applications/Follow.app/Contents/Resources/app.asar/dist/renderer/assets/main-WYXPxdLY.js:58:2141)
```

### Environment

**App Version**: 0.2.0-beta.1
**OS**: macOS
**User Agent**: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.2.0-beta.1 Chrome/130.0.6723.59 Electron/33.0.2 Safari/537.36
**Env**: electron
**Browser**: Chrome
**Session Trace Id**: `9RI-0_eQvzafPmElJ9LhJ`

### Sentry Trace ID
DJlnRR9w0qMYLQMj-FlB8

**Comment by Innei** [comment]
What content did you enter that caused the issue? I need more information.

**Comment by RizzoTho** [comment]
> What content did you enter that caused the issue? I need more information.

```CSS
p{
    margin-bottom:0.8em;
}

h1{
    font-style:italic;
    font-family:"Optima","Heiti";
    color:#5B6C5D;
    margin-bottom:0.8em;
}

body{
    font-family: 'Intel One Mono', 'TsangerJinKai02';
    background: #fbfef9;
    line-height: 25px;
    color: #191923;
    font-size: 15px;
}
```
should be this snippet I think

**Comment by Innei** [comment]
try to clean the `customCSS` field in local storage, `follow:ui` key to re-try this.

![Image](https://github.com/user-attachments/assets/5d8022df-b25e-437e-8806-687e59ac13b1)
