### ISSUE TITLE
Error: d.at is not a function

### ISSUE THREAD

**Issue by idarrine** [RSSNext/Follow#1569]
### Error

d.at is not a function

### Stack

```
TypeError: d.at is not a function
    at R (https://app.follow.is/assets/balance-DvOBLRBv.js:1:5910)
    at Ot (https://app.follow.is/assets/balance-DvOBLRBv.js:1:8742)
    at vo (https://app.follow.is/vendor/0-D0ZFORo3.js:30:16959)
    at Ka (https://app.follow.is/vendor/0-D0ZFORo3.js:32:43681)
    at Ha (https://app.follow.is/vendor/0-D0ZFORo3.js:32:39486)
    at sd (https://app.follow.is/vendor/0-D0ZFORo3.js:32:39417)
    at Jr (https://app.follow.is/vendor/0-D0ZFORo3.js:32:39276)
    at Du (https://app.follow.is/vendor/0-D0ZFORo3.js:32:35697)
    at Fi (https://app.follow.is/vendor/0-D0ZFORo3.js:32:36498)
    at mn (https://app.follow.is/vendor/0-D0ZFORo3.js:30:3258)
    at https://app.follow.is/vendor/0-D0ZFORo3.js:32:34047
```

### Environment

**App Version**: 0.2.0-beta.2
**OS**: Windows
**User Agent**: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36
**Env**: web
**Browser**: Chrome
**Session Trace Id**: `_Q8n1se7tJ2dkFkzalf7J`

### Sentry Trace ID
E4NPkNGcj7hYEhD4U1IFj

> ![Image](https://github.com/user-attachments/assets/304694eb-ff81-4456-82f1-71ea0ff2a000)

**Comment by hyoban** [comment]
It seems to be caused by the browser version being too low.

**Comment by Innei** [comment]
Follow web supports the lowest version to Chrome 97 and above, please update your browser.
