### ISSUE TITLE
Error: Cannot read properties of undefined (reading 'category')

### ISSUE THREAD

**Issue by byronzhang404** [RSSNext/Follow#1684]
### Error

Cannot read properties of undefined (reading 'category')

### Stack

```
TypeError: Cannot read properties of undefined (reading 'category')
    at file:///Applications/Follow.app/Contents/Resources/app.asar/dist/renderer/assets/layout-CgWN9WgQ.js:91:10273
    at Object.ti [as useMemo] (file:///Applications/Follow.app/Contents/Resources/app.asar/dist/renderer/assets/main-CxXzJagh.js:42:23886)
    at react_production_min.useMemo (file:///Applications/Follow.app/Contents/Resources/app.asar/dist/renderer/assets/main-CxXzJagh.js:10:7277)
    at Da (file:///Applications/Follow.app/Contents/Resources/app.asar/dist/renderer/assets/layout-CgWN9WgQ.js:91:10192)
    at Ev (file:///Applications/Follow.app/Contents/Resources/app.asar/dist/renderer/assets/layout-CgWN9WgQ.js:91:10870)
    at Nh (file:///Applications/Follow.app/Contents/Resources/app.asar/dist/renderer/assets/main-CxXzJagh.js:42:19019)
    at cj (file:///Applications/Follow.app/Contents/Resources/app.asar/dist/renderer/assets/main-CxXzJagh.js:44:3485)
    at bj (file:///Applications/Follow.app/Contents/Resources/app.asar/dist/renderer/assets/main-CxXzJagh.js:44:2618)
    at Vk (file:///Applications/Follow.app/Contents/Resources/app.asar/dist/renderer/assets/main-CxXzJagh.js:44:52512)
    at Uk (file:///Applications/Follow.app/Contents/Resources/app.asar/dist/renderer/assets/main-CxXzJagh.js:44:43991)
    at Tk (file:///Applications/Follow.app/Contents/Resources/app.asar/dist/renderer/assets/main-CxXzJagh.js:44:43912)
    at Ik (file:///Applications/Follow.app/Contents/Resources/app.asar/dist/renderer/assets/main-CxXzJagh.js:44:43752)
    at Nk (file:///Applications/Follow.app/Contents/Resources/app.asar/dist/renderer/assets/main-CxXzJagh.js:44:39720)
    at Ek (file:///Applications/Follow.app/Contents/Resources/app.asar/dist/renderer/assets/main-CxXzJagh.js:44:40622)
    at jg (file:///Applications/Follow.app/Contents/Resources/app.asar/dist/renderer/assets/main-CxXzJagh.js:42:3546)
    at file:///Applications/Follow.app/Contents/Resources/app.asar/dist/renderer/assets/main-CxXzJagh.js:44:37840
```

### Environment

**App Version**: 0.2.2-beta.0
**OS**: macOS
**User Agent**: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.2.2-beta.0 Chrome/130.0.6723.59 Electron/33.0.2 Safari/537.36
**Env**: electron
**Browser**: Chrome
**Session Trace Id**: `PrxqV50xIEMHg6Wm6JIzj`

### Sentry Trace ID
N3XYbCuE-C62Fk-pAUaj6

**Comment by Innei** [comment]
We need more information.
