### ISSUE TITLE
Error: Cannot read properties of undefined (reading 'image')

### ISSUE THREAD

**Issue by mengjii** [RSSNext/Follow#1785]
### Error

Cannot read properties of undefined (reading 'image')

### Stack

```
TypeError: Cannot read properties of undefined (reading 'image')
    at SubscriptionItems (https://app.follow.is/assets/user-profile-modal-B-c4PSMe.js:63:96)
    at Nh (https://app.follow.is/vendor/0-EeJr3raE.js:3399:7)
    at Vk (https://app.follow.is/vendor/0-EeJr3raE.js:6342:11)
    at Uk (https://app.follow.is/vendor/0-EeJr3raE.js:6036:11)
    at Tk (https://app.follow.is/vendor/0-EeJr3raE.js:6030:26)
    at Ik (https://app.follow.is/vendor/0-EeJr3raE.js:6015:7)
    at Nk (https://app.follow.is/vendor/0-EeJr3raE.js:5746:7)
    at Ek (https://app.follow.is/vendor/0-EeJr3raE.js:5800:28)
    at jg (https://app.follow.is/vendor/0-EeJr3raE.js:2708:15)
    at https://app.follow.is/vendor/0-EeJr3raE.js:5628:26
```

### Environment

**App Version**: 0.2.4-beta.0
**OS**: Windows
**User Agent**: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
**Env**: web
**Browser**: Chrome
**Session Trace Id**: `IIbUOSIhpaPj5Az2EdXQ6`

### Sentry Trace ID
wpJqbEV4LzWWk_dBxyJgj

**Comment by hyoban** [comment]
Fixed in #1759
