### ISSUE TITLE
Error: Cannot read properties of null (reading 'setClickOutSideToDismiss')

### ISSUE THREAD

**Issue by RaineySpace** [RSSNext/follow#203]
Discover RSS3

### Error

Cannot read properties of null (reading 'setClickOutSideToDismiss')

### Stack

```
TypeError: Cannot read properties of null (reading 'setClickOutSideToDismiss')
    at DiscoverFeedForm (file:///Applications/Follow.app/Contents/Resources/app.asar/dist/renderer/assets/index-IUZQgv9F.js:5827:44)
    at Nh (file:///Applications/Follow.app/Contents/Resources/app.asar/dist/renderer/assets/index-C8SW2LNY.js:3406:7)
    at Vk (file:///Applications/Follow.app/Contents/Resources/app.asar/dist/renderer/assets/index-C8SW2LNY.js:6349:12)
    at Uk (file:///Applications/Follow.app/Contents/Resources/app.asar/dist/renderer/assets/index-C8SW2LNY.js:6043:12)
    at Tk (file:///Applications/Follow.app/Contents/Resources/app.asar/dist/renderer/assets/index-C8SW2LNY.js:6037:24)
    at Ik (file:///Applications/Follow.app/Contents/Resources/app.asar/dist/renderer/assets/index-C8SW2LNY.js:6022:7)
    at Nk (file:///Applications/Follow.app/Contents/Resources/app.asar/dist/renderer/assets/index-C8SW2LNY.js:5753:7)
    at Ek (file:///Applications/Follow.app/Contents/Resources/app.asar/dist/renderer/assets/index-C8SW2LNY.js:5807:32)
    at jg (file:///Applications/Follow.app/Contents/Resources/app.asar/dist/renderer/assets/index-C8SW2LNY.js:2715:16)
    at file:///Applications/Follow.app/Contents/Resources/app.asar/dist/renderer/assets/index-C8SW2LNY.js:5635:24
```

**Comment by Innei** [comment]
Thank you for your report, and we fixed this issue in 38ab5bffafad32f97ac11a743a35be0a6012403d
