### ISSUE TITLE
Error: Cannot read properties of undefined (reading 'startsWith')

### ISSUE THREAD

**Issue by Ryuzakiend** [RSSNext/Follow#2050]
### Error

Cannot read properties of undefined (reading 'startsWith')

### Stack

```
TypeError: Cannot read properties of undefined (reading 'startsWith')
    at file:///C:/Users/xk/AppData/Local/Follow/app-0.2.6-beta0/resources/app.asar/dist/renderer/assets/recommendations-kcfPk6dN.js:1:17295
    at Array.filter (<anonymous>)
    at vs (file:///C:/Users/xk/AppData/Local/Follow/app-0.2.6-beta0/resources/app.asar/dist/renderer/assets/recommendations-kcfPk6dN.js:1:17278)
    at vu (file:///C:/Users/xk/AppData/Local/Follow/app-0.2.6-beta0/resources/app.asar/dist/renderer/assets/main-fFkEPEaQ.js:42:18838)
    at Ud (file:///C:/Users/xk/AppData/Local/Follow/app-0.2.6-beta0/resources/app.asar/dist/renderer/assets/main-fFkEPEaQ.js:44:48120)
    at $d (file:///C:/Users/xk/AppData/Local/Follow/app-0.2.6-beta0/resources/app.asar/dist/renderer/assets/main-fFkEPEaQ.js:44:43476)
    at U2 (file:///C:/Users/xk/AppData/Local/Follow/app-0.2.6-beta0/resources/app.asar/dist/renderer/assets/main-fFkEPEaQ.js:44:43402)
    at Dl (file:///C:/Users/xk/AppData/Local/Follow/app-0.2.6-beta0/resources/app.asar/dist/renderer/assets/main-fFkEPEaQ.js:44:43249)
    at Wu (file:///C:/Users/xk/AppData/Local/Follow/app-0.2.6-beta0/resources/app.asar/dist/renderer/assets/main-fFkEPEaQ.js:44:39287)
    at jd (file:///C:/Users/xk/AppData/Local/Follow/app-0.2.6-beta0/resources/app.asar/dist/renderer/assets/main-fFkEPEaQ.js:44:40180)
    at Pa (file:///C:/Users/xk/AppData/Local/Follow/app-0.2.6-beta0/resources/app.asar/dist/renderer/assets/main-fFkEPEaQ.js:42:3505)
    at file:///C:/Users/xk/AppData/Local/Follow/app-0.2.6-beta0/resources/app.asar/dist/renderer/assets/main-fFkEPEaQ.js:44:37451
```

### Environment

**App Version**: 0.2.6-beta.0
**OS**: Windows
**User Agent**: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.2.6-beta.0 Chrome/130.0.6723.118 Electron/33.2.0 Safari/537.36
**Env**: electron
**Browser**: Chrome
**Session Trace Id**: `MFHJ9RXwGzr-n0vdV8OMR`

### Sentry Trace ID
0mWun8fL8Ie90Of0jFNDs

**Comment by hyoban** [comment]
Can you provide more information on how to reproduce this?
