### ISSUE TITLE
Error: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.

### ISSUE THREAD

**Issue by laozhangge** [RSSNext/Follow#2121]
### Error

Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.

### Stack

```
NotFoundError: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
    at Yi (https://app.follow.is/vendor/0-270N51eK.js:40:25559)
    at Yi (https://app.follow.is/vendor/0-270N51eK.js:40:25634)
    at Yi (https://app.follow.is/vendor/0-270N51eK.js:40:25634)
    at Hn (https://app.follow.is/vendor/0-270N51eK.js:40:30780)
    at ec (https://app.follow.is/vendor/0-270N51eK.js:40:27623)
    at xn (https://app.follow.is/vendor/0-270N51eK.js:40:27502)
    at ec (https://app.follow.is/vendor/0-270N51eK.js:40:27615)
    at xn (https://app.follow.is/vendor/0-270N51eK.js:40:27502)
    at ec (https://app.follow.is/vendor/0-270N51eK.js:40:27812)
    at xn (https://app.follow.is/vendor/0-270N51eK.js:40:27502)
    at ec (https://app.follow.is/vendor/0-270N51eK.js:40:27812)
    at xn (https://app.follow.is/vendor/0-270N51eK.js:40:27502)
    at ec (https://app.follow.is/vendor/0-270N51eK.js:40:27615)
    at xn (https://app.follow.is/vendor/0-270N51eK.js:40:27502)
    at ec (https://app.follow.is/vendor/0-270N51eK.js:40:27812)
    at xn (https://app.follow.is/vendor/0-270N51eK.js:40:27502)
    at ec (https://app.follow.is/vendor/0-270N51eK.js:40:27615)
    at xn (https://app.follow.is/vendor/0-270N51eK.js:40:27502)
    at ec (https://app.follow.is/vendor/0-270N51eK.js:40:30547)
    at xn (https://app.follow.is/vendor/0-270N51eK.js:40:27502)
    at ec (https://app.follow.is/vendor/0-270N51eK.js:40:27615)
    at xn (https://app.follow.is/vendor/0-270N51eK.js:40:27502)
    at ec (https://app.follow.is/vendor/0-270N51eK.js:40:30547)
    at xn (https://app.follow.is/vendor/0-270N51eK.js:40:27502)
    at ec (https://app.follow.is/vendor/0-270N51eK.js:40:27615)
    at xn (https://app.follow.is/vendor/0-270N51eK.js:40:27502)
    at ec (https://app.follow.is/vendor/0-270N51eK.js:40:30547)
    at xn (https://app.follow.is/vendor/0-270N51eK.js:40:27502)
    at ec (https://app.follow.is/vendor/0-270N51eK.js:40:27615)
    at xn (https://app.follow.is/vendor/0-270N51eK.js:40:27502)
    at ec (https://app.follow.is/vendor/0-270N51eK.js:40:27812)
    at xn (https://app.follow.is/vendor/0-270N51eK.js:40:27502)
    at ec (https://app.follow.is/vendor/0-270N51eK.js:40:27812)
    at xn (https://app.follow.is/vendor/0-270N51eK.js:40:27502)
    at ec (https://app.follow.is/vendor/0-270N51eK.js:40:27615)
    at xn (https://app.follow.is/vendor/0-270N51eK.js:40:27502)
    at ec (https://app.follow.is/vendor/0-270N51eK.js:40:27615)
    at xn (https://app.follow.is/vendor/0-270N51eK.js:40:27502)
    at ec (https://app.follow.is/vendor/0-270N51eK.js:40:27615)
    at xn (https://app.follow.is/vendor/0-270N51eK.js:40:27502)
    at ec (https://app.follow.is/vendor/0-270N51eK.js:40:30547)
    at xn (https://app.follow.is/vendor/0-270N51eK.js:40:27502)
    at ec (https://app.follow.is/vendor/0-270N51eK.js:40:27812)
    at xn (https://app.follow.is/vendor/0-270N51eK.js:40:27502)
    at ec (https://app.follow.is/vendor/0-270N51eK.js:40:27615)
    at xn (https://app.follow.is/vendor/0-270N51eK.js:40:27502)
    at ec (https://app.follow.is/vendor/0-270N51eK.js:40:30547)
    at xn (https://app.follow.is/vendor/0-270N51eK.js:40:27502)
    at ec (https://app.follow.is/vendor/0-270N51eK.js:40:27615)
    at xn (https://app.follow.is/vendor/0-270N51eK.js:40:27502)
```

### Environment

**App Version**: 0.2.6-beta.0
**OS**: Windows
**User Agent**: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
**Env**: web
**Browser**: Chrome
**Session Trace Id**: `4MArVkUXIbv8Jx6g2UoUh`

### Sentry Trace ID
rixDMqjS-kD4kHBMNgxFP

**Comment by hyoban** [comment]
Can you provide more information on how to reproduce this issue?

**Comment by hyoban** [comment]
Related to https://github.com/facebook/react/issues/11538
