### ISSUE TITLE
Render error

### ISSUE THREAD

**Issue by henryustc** [RSSNext/Follow#2136]
### Error

Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.

### Stack

```
NotFoundError: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
    at Yi (https://app.follow.is/vendor/0-Ba37Dwhg.js:40:25559)
    at Yi (https://app.follow.is/vendor/0-Ba37Dwhg.js:40:25634)
    at Yi (https://app.follow.is/vendor/0-Ba37Dwhg.js:40:25634)
    at Yi (https://app.follow.is/vendor/0-Ba37Dwhg.js:40:25634)
    at Yi (https://app.follow.is/vendor/0-Ba37Dwhg.js:40:25634)
    at Yi (https://app.follow.is/vendor/0-Ba37Dwhg.js:40:25634)
    at Hn (https://app.follow.is/vendor/0-Ba37Dwhg.js:40:30780)
    at ec (https://app.follow.is/vendor/0-Ba37Dwhg.js:40:27623)
    at xn (https://app.follow.is/vendor/0-Ba37Dwhg.js:40:27502)
    at ec (https://app.follow.is/vendor/0-Ba37Dwhg.js:40:27615)
    at xn (https://app.follow.is/vendor/0-Ba37Dwhg.js:40:27502)
    at ec (https://app.follow.is/vendor/0-Ba37Dwhg.js:40:27615)
    at xn (https://app.follow.is/vendor/0-Ba37Dwhg.js:40:27502)
    at ec (https://app.follow.is/vendor/0-Ba37Dwhg.js:40:27812)
    at xn (https://app.follow.is/vendor/0-Ba37Dwhg.js:40:27502)
    at ec (https://app.follow.is/vendor/0-Ba37Dwhg.js:40:27812)
    at xn (https://app.follow.is/vendor/0-Ba37Dwhg.js:40:27502)
    at ec (https://app.follow.is/vendor/0-Ba37Dwhg.js:40:27615)
    at xn (https://app.follow.is/vendor/0-Ba37Dwhg.js:40:27502)
    at ec (https://app.follow.is/vendor/0-Ba37Dwhg.js:40:27812)
    at xn (https://app.follow.is/vendor/0-Ba37Dwhg.js:40:27502)
    at ec (https://app.follow.is/vendor/0-Ba37Dwhg.js:40:27812)
    at xn (https://app.follow.is/vendor/0-Ba37Dwhg.js:40:27502)
    at ec (https://app.follow.is/vendor/0-Ba37Dwhg.js:40:28927)
    at xn (https://app.follow.is/vendor/0-Ba37Dwhg.js:40:27502)
    at ec (https://app.follow.is/vendor/0-Ba37Dwhg.js:40:27615)
    at xn (https://app.follow.is/vendor/0-Ba37Dwhg.js:40:27502)
    at ec (https://app.follow.is/vendor/0-Ba37Dwhg.js:40:27615)
    at xn (https://app.follow.is/vendor/0-Ba37Dwhg.js:40:27502)
    at ec (https://app.follow.is/vendor/0-Ba37Dwhg.js:40:30547)
    at xn (https://app.follow.is/vendor/0-Ba37Dwhg.js:40:27502)
    at ec (https://app.follow.is/vendor/0-Ba37Dwhg.js:40:30547)
    at xn (https://app.follow.is/vendor/0-Ba37Dwhg.js:40:27502)
    at ec (https://app.follow.is/vendor/0-Ba37Dwhg.js:40:27615)
    at xn (https://app.follow.is/vendor/0-Ba37Dwhg.js:40:27502)
    at ec (https://app.follow.is/vendor/0-Ba37Dwhg.js:40:30547)
    at xn (https://app.follow.is/vendor/0-Ba37Dwhg.js:40:27502)
    at ec (https://app.follow.is/vendor/0-Ba37Dwhg.js:40:30547)
    at xn (https://app.follow.is/vendor/0-Ba37Dwhg.js:40:27502)
    at ec (https://app.follow.is/vendor/0-Ba37Dwhg.js:40:30547)
    at xn (https://app.follow.is/vendor/0-Ba37Dwhg.js:40:27502)
    at ec (https://app.follow.is/vendor/0-Ba37Dwhg.js:40:27615)
    at xn (https://app.follow.is/vendor/0-Ba37Dwhg.js:40:27502)
    at ec (https://app.follow.is/vendor/0-Ba37Dwhg.js:40:27615)
    at xn (https://app.follow.is/vendor/0-Ba37Dwhg.js:40:27502)
    at ec (https://app.follow.is/vendor/0-Ba37Dwhg.js:40:30547)
    at xn (https://app.follow.is/vendor/0-Ba37Dwhg.js:40:27502)
    at ec (https://app.follow.is/vendor/0-Ba37Dwhg.js:40:27812)
    at xn (https://app.follow.is/vendor/0-Ba37Dwhg.js:40:27502)
    at ec (https://app.follow.is/vendor/0-Ba37Dwhg.js:40:30547)
```

### Environment

**App Version**: 0.2.7-beta.0
**OS**: macOS
**User Agent**: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 Edg/131.0.0.0
**Env**: web
**Browser**: Microsoft Edge
**Session Trace Id**: `OidGytI3A0sm9S16NCXs3`

**Comment by TonyRL** [comment]
Duplicate of #2121
