### ISSUE TITLE
Error: Cannot read properties of undefined (reading 'iconClassName')

### ISSUE THREAD

**Issue by bugubuguga** [RSSNext/Follow#2180]
### Error

Cannot read properties of undefined (reading 'iconClassName')

### Stack

```
TypeError: Cannot read properties of undefined (reading 'iconClassName')
    at file:///C:/Users/muche/AppData/Local/Follow/app-0.2.6-beta0/resources/app.asar/dist/renderer/assets/main-fFkEPEaQ.js:218:15935
    at Array.map (<anonymous>)
    at LoginModalContent (file:///C:/Users/muche/AppData/Local/Follow/app-0.2.6-beta0/resources/app.asar/dist/renderer/assets/main-fFkEPEaQ.js:218:15424)
    at vu (file:///C:/Users/muche/AppData/Local/Follow/app-0.2.6-beta0/resources/app.asar/dist/renderer/assets/main-fFkEPEaQ.js:42:18838)
    at Au (file:///C:/Users/muche/AppData/Local/Follow/app-0.2.6-beta0/resources/app.asar/dist/renderer/assets/main-fFkEPEaQ.js:44:3477)
    at Ud (file:///C:/Users/muche/AppData/Local/Follow/app-0.2.6-beta0/resources/app.asar/dist/renderer/assets/main-fFkEPEaQ.js:44:48994)
    at $d (file:///C:/Users/muche/AppData/Local/Follow/app-0.2.6-beta0/resources/app.asar/dist/renderer/assets/main-fFkEPEaQ.js:44:43476)
    at U2 (file:///C:/Users/muche/AppData/Local/Follow/app-0.2.6-beta0/resources/app.asar/dist/renderer/assets/main-fFkEPEaQ.js:44:43402)
    at Dl (file:///C:/Users/muche/AppData/Local/Follow/app-0.2.6-beta0/resources/app.asar/dist/renderer/assets/main-fFkEPEaQ.js:44:43249)
    at Wu (file:///C:/Users/muche/AppData/Local/Follow/app-0.2.6-beta0/resources/app.asar/dist/renderer/assets/main-fFkEPEaQ.js:44:39287)
    at jd (file:///C:/Users/muche/AppData/Local/Follow/app-0.2.6-beta0/resources/app.asar/dist/renderer/assets/main-fFkEPEaQ.js:44:40180)
    at Pa (file:///C:/Users/muche/AppData/Local/Follow/app-0.2.6-beta0/resources/app.asar/dist/renderer/assets/main-fFkEPEaQ.js:42:3505)
    at file:///C:/Users/muche/AppData/Local/Follow/app-0.2.6-beta0/resources/app.asar/dist/renderer/assets/main-fFkEPEaQ.js:44:37451
```

### Environment

**App Version**: 0.2.6-beta.0
**OS**: Windows
**User Agent**: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.2.6-beta.0 Chrome/130.0.6723.118 Electron/33.2.0 Safari/537.36
**Env**: electron
**Browser**: Chrome
**Session Trace Id**: `rr6c9XEsdwqhOVMcG0Na_`

### Sentry Trace ID
qIAk7nQSt9M2wTCv5tZ--

**Comment by hyoban** [comment]
This issue is fixed in 0.2.7, Please try to update to the latest
