### ISSUE TITLE
[Bug]: Parsing the feed content may result in an incorrect HTML structure

### ISSUE THREAD

**Issue by TonyRL** [RSSNext/Follow#223]
### Error

No QueryClient set, use QueryClientProvider to set one

### Stack

```
Error: No QueryClient set, use QueryClientProvider to set one
    at useQueryClient (file:///AppData/Local/Follow/app-0.0.1-alpha6/resources/app.asar/dist/renderer/assets/index-u3ry5diE.js:21229:11)
    at useBaseQuery (file:///AppData/Local/Follow/app-0.0.1-alpha6/resources/app.asar/dist/renderer/assets/index-u3ry5diE.js:21307:19)
    at useQuery (file:///AppData/Local/Follow/app-0.0.1-alpha6/resources/app.asar/dist/renderer/assets/index-u3ry5diE.js:21358:10)
    at useAuthQuery (file:///AppData/Local/Follow/app-0.0.1-alpha6/resources/app.asar/dist/renderer/assets/index-u3ry5diE.js:21400:5)
    at MarkdownLink (file:///AppData/Local/Follow/app-0.0.1-alpha6/resources/app.asar/dist/renderer/assets/Markdown-sxDt4h3m.js:6713:3)
    at Db$1 (file:///AppData/Local/Follow/app-0.0.1-alpha6/resources/app.asar/dist/renderer/assets/index-CFo79uFw.js:1004:12)
    at Gb$1 (file:///AppData/Local/Follow/app-0.0.1-alpha6/resources/app.asar/dist/renderer/assets/index-CFo79uFw.js:1041:9)
    at X$1 (file:///AppData/Local/Follow/app-0.0.1-alpha6/resources/app.asar/dist/renderer/assets/index-CFo79uFw.js:1188:9)
    at Gb$1 (file:///AppData/Local/Follow/app-0.0.1-alpha6/resources/app.asar/dist/renderer/assets/index-CFo79uFw.js:1052:12)
    at X$1 (file:///AppData/Local/Follow/app-0.0.1-alpha6/resources/app.asar/dist/renderer/assets/index-CFo79uFw.js:1188:9)
    at Hb$1 (file:///AppData/Local/Follow/app-0.0.1-alpha6/resources/app.asar/dist/renderer/assets/index-CFo79uFw.js:1233:12)
    at Ib$1 (file:///AppData/Local/Follow/app-0.0.1-alpha6/resources/app.asar/dist/renderer/assets/index-CFo79uFw.js:1224:7)
    at X$1 (file:///AppData/Local/Follow/app-0.0.1-alpha6/resources/app.asar/dist/renderer/assets/index-CFo79uFw.js:1199:7)
    at Hb$1 (file:///AppData/Local/Follow/app-0.0.1-alpha6/resources/app.asar/dist/renderer/assets/index-CFo79uFw.js:1233:12)
    at Gb$1 (file:///AppData/Local/Follow/app-0.0.1-alpha6/resources/app.asar/dist/renderer/assets/index-CFo79uFw.js:1060:5)
    at X$1 (file:///AppData/Local/Follow/app-0.0.1-alpha6/resources/app.asar/dist/renderer/assets/index-CFo79uFw.js:1188:9)
    at Hb$1 (file:///AppData/Local/Follow/app-0.0.1-alpha6/resources/app.asar/dist/renderer/assets/index-CFo79uFw.js:1233:12)
    at Ib$1 (file:///AppData/Local/Follow/app-0.0.1-alpha6/resources/app.asar/dist/renderer/assets/index-CFo79uFw.js:1224:7)
    at X$1 (file:///AppData/Local/Follow/app-0.0.1-alpha6/resources/app.asar/dist/renderer/assets/index-CFo79uFw.js:1199:7)
    at Cb$1 (file:///AppData/Local/Follow/app-0.0.1-alpha6/resources/app.asar/dist/renderer/assets/index-CFo79uFw.js:1296:13)
    at Tb$1 (file:///AppData/Local/Follow/app-0.0.1-alpha6/resources/app.asar/dist/renderer/assets/index-CFo79uFw.js:1531:3)
    at reactDomServerLegacy_browser_production_min.renderToString (file:///AppData/Local/Follow/app-0.0.1-alpha6/resources/app.asar/dist/renderer/assets/index-CFo79uFw.js:1556:10)
    at pre (file:///AppData/Local/Follow/app-0.0.1-alpha6/resources/app.asar/dist/renderer/assets/index-CFo79uFw.js:14743:46)
    at Nh (file:///AppData/Local/Follow/app-0.0.1-alpha6/resources/app.asar/dist/renderer/assets/index-u3ry5diE.js:3406:7)
    at Vk (file:///AppData/Local/Follow/app-0.0.1-alpha6/resources/app.asar/dist/renderer/assets/index-u3ry5diE.js:6349:12)
    at Uk (file:///AppData/Local/Follow/app-0.0.1-alpha6/resources/app.asar/dist/renderer/assets/index-u3ry5diE.js:6043:12)
    at Tk (file:///AppData/Local/Follow/app-0.0.1-alpha6/resources/app.asar/dist/renderer/assets/index-u3ry5diE.js:6037:24)
    at Ik (file:///AppData/Local/Follow/app-0.0.1-alpha6/resources/app.asar/dist/renderer/assets/index-u3ry5diE.js:6022:7)
    at Nk (file:///AppData/Local/Follow/app-0.0.1-alpha6/resources/app.asar/dist/renderer/assets/index-u3ry5diE.js:5753:7)
    at Ek (file:///AppData/Local/Follow/app-0.0.1-alpha6/resources/app.asar/dist/renderer/assets/index-u3ry5diE.js:5807:32)
    at jg (file:///AppData/Local/Follow/app-0.0.1-alpha6/resources/app.asar/dist/renderer/assets/index-u3ry5diE.js:2715:16)
    at file:///AppData/Local/Follow/app-0.0.1-alpha6/resources/app.asar/dist/renderer/assets/index-u3ry5diE.js:5635:24
```

### Steps to reproduce

1. Click on an article item
2. Keep pressing down key and up key
3. Observe the article panel

Feed URL: https://web.follow.is/feed/41440449356332035/

### Screenshot

<details>
<summary>Screenshot</summary>

![Follow](https://github.com/user-attachments/assets/bd198520-7ecc-4b89-9578-752bee98d115)
</details>

**Comment by Innei** [comment]
@DIYgod 

Entry Id: 46200856680822784

Entry Content parsing problem, <pre> is not closed. This is shown in the figure below.
![CleanShot 2024-08-15 at 2  59 22@2x](https://github.com/user-attachments/assets/1c62355f-0c86-4dae-b34a-66d7c4126af9)

Original Feed Entry:
![CleanShot 2024-08-15 at 3  01 03@2x](https://github.com/user-attachments/assets/ee668b5f-c1e1-42c2-9c80-f6b26a1ca10e)

Local parsed entry:
![CleanShot 2024-08-15 at 3  02 20@2x](https://github.com/user-attachments/assets/a305d878-470d-44e4-a7e5-51351aee6179)


But this cannot be reproduced locally. Maybe this Feed Entry has been modified. Maybe we need to refresh the database data.

**Comment by TonyRL** [comment]
> Maybe this Feed Entry has been modified.

The feed entry is provided by Readability.

**Comment by Innei** [comment]
> > Maybe this Feed Entry has been modified.
> 
> The feed entry is provided by Readability.

In production databases, even without Readability, HTML parsing is problematic

**Comment by Innei** [comment]
I catch the parsing and rendering error, but if the format is wrong, the render result will not be expected.
